services:

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data


  lovelink-backend:
    build:
      context: ./backend
    env_file:
      - .env
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      - postgres
    volumes:
      - static_volume:/app/staticfiles


  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/staticfiles
    env_file:
      - .env
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - lovelink-backend


  redis:
    image: redis:latest
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"


  celery:
    build:
      context: ./backend
    env_file:
      - .env
    command: celery -A lovelink worker -l info
    depends_on:
      - redis
      - lovelink-backend


  celery-beat:
    build:
      context: ./backend
    env_file:
      - .env
    command: celery -A lovelink beat -l info
    depends_on:
      - redis
      - lovelink-backend


volumes:
  pg_data:
  static_volume: