version: latest
x-environment-deafault: &environment-defaults
  DEBUG: "True"
  SECRET_KEY: "django-insecure-5zxs=ha2@6_u%1--ypocyk4dxs+&^jnv)frt3khw_&nyq@2dwn"
  DB_NAME: lovelinkDB
  DB_USER: user_lovelinkDB
  DB_PASSWORD: 1415342
  DB_HOST: postgres
  DB_PORT: 5432
  EMAIL_HOST: smtp.gmail.com
  EMAIL_PORT: 587
  EMAIL_HOST_USER: 290819allo@gmail.com
  EMAIL_HOST_PASSWORD: "zhyd dbsr aggj wlcl"
  EMAIL_USE_TLS: "True"
  STRIPE_PUBLISHABLE_KEY: "pk_test_51OCIWtF91pZqOJqXB2LAAaRc9x3oAYdKtusH3nAXdhsoWBLNL1XvIBQpaAUrLws3eBnSbplGpijgncZvNcag6PIl00UayyjiT9"
  STRIPE_SECRET_KEY: "sk_test_51OCIWtF91pZqOJqX5thDPLqAfNODMJw1uHw46oBLNHfNNhOVkboKOvq1r0qjvjQCAVQPiibR8wmMAq6W2ENH1oeN009ZaOkDYl"
  STRIPE_ENDPOINT_SECRET: "whsec_8e953fd27d027957bbc83fb1339223cdf5d52d52dd8d794f38b06931c69e3223"
  REDIS_HOST: redis
  REDIS_PORT: 6379


services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user_lovelinkDB
      POSTGRES_PASSWORD: 1415342
      POSTGRES_DB: lovelinkDB
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - lovelink-network

  lovelink-backend:
    build:
      context: ./backend
    ports:
      - "8001:8000"
    depends_on:
      - postgres
    environment:
      <<: *environment-defaults
    volumes:
      - static_volume:/app/staticfiles
    networks:
      - lovelink-network


  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/staticfiles
    ports:
      - "80:80"
    depends_on:
      - lovelink-backend
    networks:
      - lovelink-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - lovelink-network

  celery:
    build:
      context: ./backend
    command: celery -A lovelink worker -l info
    depends_on:
      - redis
      - postgres
    environment:
      <<: *environment-defaults
    networks:
      - lovelink-network

  celery-beat:
    build:
      context: ./backend
    command: celery -A lovelink beat -l info

    depends_on:
      - redis
      - postgres
    environment:
      <<: *environment-defaults
    networks:
      - lovelink-network

volumes:
  pg_data:
  static_volume:

networks:
  lovelink-network:
    driver: bridge
