# Generated by Django 4.2.7 on 2023-12-29 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_chat_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
