# Generated by Django 4.2.7 on 2024-01-19 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usercoinsmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCoinsModel',
        ),
    ]
