# Generated by Django 4.2.7 on 2024-01-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_usercoinsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coins',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
